### ISSUE TITLE
Push callbacks not working, it's not getting called

### ISSUE THREAD

**Issue by priyabratap** [WebEngage/webengage-flutter#11]
Push callbacks not working, it's not getting called. All rest are working.

//Push click stream listener
      _webEngagePlugin.pushStream.listen((event) {
        String deepLink = event.deepLink;
        Map<String, dynamic> messagePayload = event.payload;
      });

In my code I have put one more print statement to see payload.

**Comment by manish-cashify** [comment]
I have been using latest SDK webengage_flutter 1.0.3, still facing same issue. Push click callback not working when app is closed/terminated, it works only when app is in foreground.

**Comment by SarthakWebEngage** [comment]
@priyabratap  I hope you have followed the [docs](https://docs.webengage.com/docs/flutter-callbacks).
Kindly, share your implementation screenshot of main.dart to [sarthak.sharma@webklipper.com](mailto:sarthak.sharma@webklipper.com).
