### ISSUE TITLE
Module compiled with Swift 5.1.3 cannot be imported by the Swift 5.5.1 

### ISSUE THREAD

**Issue by developerCode11** [WebEngage/webengage-flutter#13]
I got this error. when I was trying to add WebEngage into the project.

pub get ✅ 
pod install ✅ 
Xcode build ⛔

My assumption is that something is not good with the WebEngage SDK version. That wasn't compatible with my latest Xcode version. 

That was what I assume, but Let me know the team how I can resolve this.

Thank you

![Screenshot 2022-01-19 at 6 06 53 PM](https://user-images.githubusercontent.com/89451857/150132143-4d60071a-b420-4630-9ea1-0be6a6f8a67f.png)
.

**Comment by snehmehta** [comment]
Hey @developerCode11,
I am facing the same issue. If you have resolved it, please share the solution.

**Comment by developerCode11** [comment]
target.build_configurations.each do |build_configuration|
    build_configuration.build_settings['EXCLUDED_ARCHS[sdk=iphonesimulator*]'] = 'arm64 i386'
  end 

  add this lines in pod file then it will work.
