### ISSUE TITLE
android push notification action callback not working

### ISSUE THREAD

**Issue by salahamassi** [WebEngage/webengage-flutter#16]
I tried to perform some custom code when received a push notification from web engage  

```dart
  _webEngagePlugin.pushActionStream.listen(_onWebEngagePush);
```

```dart
  void _onWebEngagePush(PushPayload event) {
    debugPrint('webEngage push stream: ${event.toString()}');
    String? deepLink = event.deepLink;
    if (deepLink != null && deepLink.isNotEmpty) {
      sl<UniLinksIntegration>().handleDynamicLinks(Uri.tryParse(deepLink));
    }
}
```

but pushActionStream doesn't receive any event when I click the received notification 

Flutter doctor output:

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel unknown, 2.10.5, on macOS 12.0 21A344 darwin-arm, locale en-PS)
[✓] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 13.4)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.2)
[✓] Connected device (2 available)
    ! Error: Salah iPhone 12 is not connected. Xcode will continue when Salah iPhone 12 is connected. (code -13)
[✓] HTTP Host Availability

• No issues found!
```

**Comment by SarthakWebEngage** [comment]
@salahamassi I hope you have followed the [docs](https://docs.webengage.com/docs/flutter-callbacks).
Kindly, share your implementation screenshot of main.dart to sarthak.sharma@webklipper.com.

**Comment by milind-yocket** [comment]
Any update on the above issue?

**Comment by SarthakWebEngage** [comment]
Hi @milind-yocket,
It works perfectly on our side, you can explore the Example application for your reference. If still, you are facing issues, kindly contact our support team or mail me the details on [sarthak.sharma@webklipper.com](mailto:sarthak.sharma@webklipper.com).

**Comment by milind-yocket** [comment]
@SarthakWebEngage We are already using FCM notification & related navigation handling. 
on top of that, we also want WebEngage notification & navigation handling, should both work fine with each other? 
Also, do you have any resources or examples that showcase both handlings together?

**Comment by SarthakWebEngage** [comment]
If that is the case, then you need to place the WebEngage FCM code inside the Firebase Messaging Service class. As per FCM, no two services can work together, so you need to do the refactoring.
@milind-yocket

**Comment by SarthakWebEngage** [comment]
@milind-yocket We've updated our [docs](https://docs.webengage.com/docs/flutter-push-notifications#integrating-webengage-with-your-flutter-android-app-fcm-enabled) with the necessary steps if your project is already use Flutter FCM plugin.

Let us know, if you need any help.

**Comment by sankarsham** [comment]
I implemented but background notification working fine but when I click on notification not working...same thing working fine fcm
@SarthakWebEngage

**Comment by SarthakWebEngage** [comment]
Hi @sankarsham ,
Kindly help me with the detailed problem statement by reaching out to our [support team]([support@webengage.com](mailto:support@webengage.com)).
