### ISSUE TITLE
Upgrade WebEngage Break iOS  project run

### ISSUE THREAD

**Issue by salahamassi** [WebEngage/webengage-flutter#18]
after upgrade webengge 

![image](https://user-images.githubusercontent.com/17902030/187198616-85115958-3963-4d5a-9c48-75dd6592ed13.png)

and running the flutter project this error appears 

<img width="1114" alt="image" src="https://user-images.githubusercontent.com/17902030/187198884-8a890c29-3696-4a02-b751-a4f6953b43b8.png">

**Comment by Pomis** [comment]
Having the same problem. Reverting to the old version in podfile.lock helped:
```
  - WebEngage (5.2.11):
    - WebEngage/Xcode11 (= 5.2.11)
  - WebEngage/Xcode11 (5.2.11)
```

**Comment by abdoosaed** [comment]
@HassanBalousha

**Comment by SarthakWebEngage** [comment]
Hi @salahamassi and @abdoosaed,
Our Flutter plugin does not download XCFramework for now, however you can change the plugin podspec value from.
`s.dependency 'WebEngage'` -> `s.dependency 'WebEngage/XCFramework'`

This should solve this one.

**Comment by SarthakWebEngage** [comment]
Kindly upgrade the plugin to 1.2.0.
