### ISSUE TITLE
build.gradle Deprecated

### ISSUE THREAD

**Issue by astraube** [WebEngage/webengage-flutter#21]
No build.gradle ### classpath is outdated, and repositories still using ### jcenter()

**Comment by brunosmm** [comment]
Hello WebEngage team!

Our building is falling due jcenter problems, this is direct broken our pipeline and stop our production releases!!
Jcenter is a completely out dated plugin lib, can you fix this asap?

![image](https://user-images.githubusercontent.com/1554850/199009182-1834eab8-39ab-42de-9501-48124f9ae678.png)

**Comment by brunosmm** [comment]
Updating to the lates version 1.2.1 still throws an error com jcentral...

![image](https://user-images.githubusercontent.com/1554850/199041179-dcf97ca7-88c5-4132-840e-46fb2f9acc64.png)
