### ISSUE TITLE
Lexical or Preprocessor Issue (Xcode): 'WebEngage/WebEngage.h' file not found

### ISSUE THREAD

**Issue by KumarArab** [WebEngage/webengage-flutter#25]
So I was using flutter v2.10.3 and for some reason I switched to 2.10.4 and again back to 2.10.3. 
No I am getting this error while running on iOS device/ Simulator.

I tried latest version also, still the issue persists.

ERROR:

```
Uncategorized (Xcode): Command CompileSwiftSources failed with a nonzero exit code

Lexical or Preprocessor Issue (Xcode): 'WebEngage/WebEngage.h' file not found
/Users/arabkumar/.pub-cache/hosted/pub.dartlang.org/webengage_flutter-1.2.1/ios/Classes/WebEngagePlugin.h:1:8
2

Could not build the application for the simulator.
Error launching application on iPhone 13.
```

**Comment by MustafaGamalAbbas** [comment]
+1

**Comment by MilindWebEngage** [comment]
You will get this issue if you are using the Xcode version 13, try to upgrade the Xcode version to 13.4 or to the latest one.
We are working on this issue as it only occurs on Xcode 13, for now you can upgrade the Xcode version.

**Comment by KumarArab** [comment]
Yes, upgrading  XCode solved the issue

**Comment by animeshflutterdev** [comment]
Getting the same error with using XCode version 15.3

**Comment by MilindWebEngage** [comment]
@animeshflutterdev which webengage-flutter version you are using?

**Comment by animeshflutterdev** [comment]
the latest one, webengage_flutter: ^1.5.0 and flutter version is 3.22.3.

**Comment by MilindWebEngage** [comment]
@animeshflutterdev Can you share the latest screenshots of the errors—one from Android Studio and one from Xcode?

**Comment by animeshflutterdev** [comment]
![f3c19 1725947255 6226 web rediffmail com](https://github.com/user-attachments/assets/5bee8802-6d39-4844-b2af-69ea14351c34)


Is it helpful ?
