### ISSUE TITLE
-[WEGConfig doSession]_block_invoke [Line 725]: Notification Session Rule Failed for ja49mo

### ISSUE THREAD

**Issue by binSaed** [WebEngage/webengage-flutter#27]
![Screenshot 2022-12-06 at 3 33 56 AM](https://user-images.githubusercontent.com/33700292/205786572-f3370e79-01c0-4dc7-b52d-e478fe55e8a9.png)

**Comment by MilindWebEngage** [comment]
@binSaed Please check the .p12 or .p8 that you have uploaded on WebEngage dashboard (production or environment) are valid or not by using the below application for iOS - https://github.com/onmyway133/PushNotifications#ios-authentication-token.
If you are getting the success and receiving the notification from above application and still not receiving it from the WebEngage Dashboard and getting error -then you can reach out to us on [support@webengage.com](mailto:support@webengage.com).

If you are also getting the same error from above application then it might be the issue with your .p8 or .p12 file

**Comment by SarthakWebEngage** [comment]
Due to the lack of activity, the issue is closed.
