### ISSUE TITLE
problem in documents for flutter push notifications

### ISSUE THREAD

**Issue by mahanabd** [WebEngage/webengage-flutter#28]
I use the document from the link:
https://docs.webengage.com/docs/flutter-push-notifications
It has two problems:
The first one in the Doc has 2 titles "Integrating WebEngage with your Flutter Android App". And I'm not sure which part to use.
Because service is not set in the manifest in the second part of the service.

After I used the first part, the program encountered the following error:

`/Users/mahanabedini/AndroidStudioProjects/doki-app-new26/android/app/src/debug/AndroidManifest.xml Error:
	android:exported needs to be explicitly specified for element <service#es.mhholding.doki_app.MyFirebaseMessagingService>. Apps targeting Android 12 and higher are required to specify an explicit value for `android:exported` when the corresponding component has an intent filter defined. See https://developer.android.com/guide/topics/manifest/activity-element#exported for details.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:processDebugMainManifest'.
> Manifest merger failed with multiple errors, see logs

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 7s
Exception: Gradle task assembleDebug failed with exit code 1`

update:
and is think step5 in part one must change like this in kotlin:

`import com.google.firebase.messaging.FirebaseMessagingService
import com.google.firebase.messaging.RemoteMessage
import com.webengage.sdk.android.WebEngage

class MyFirebaseMessagingService : FirebaseMessagingService() {
    override fun onMessageReceived(remoteMessage: RemoteMessage) {
        val data = remoteMessage.data
        if (data != null) {
            if (data.containsKey("source") && "webengage" == data["source"]) {
                WebEngage.get().receive(data)
            }
        }
    }

        override fun onNewToken(s: String) {
        super.onNewToken(s)
        WebEngage.get().setRegistrationID(s)
    }
}`

I would appreciate it if you updated the document.

**Comment by MilindWebEngage** [comment]
@mahanabd 
1. For your first point - The first one in the Doc has 2 titles "Integrating WebEngage with your Flutter Android App".
If you will check the docs it is written 
**_Integrating WebEngage with your Flutter Android App (FCM not integrated)_** and
**_Integrating WebEngage with your Flutter Android App (FCM integrated)_**

So if you are using firebase in your project then follow 2nd one else follow the 1st one.

for error :- please add exported = "true" in MyFirebaseMessagingService in Manifest file

so the code will look like below in Manifest file of android

```
<service android:name=".MyFirebaseMessagingService"
            android:exported="true">
            <intent-filter>
                <action android:name="com.google.firebase.MESSAGING_EVENT" />
            </intent-filter>
</service>
```

And We will update our docs for the same and the below kotlin code you have mentioned.
Thank You 👍

**Comment by SarthakWebEngage** [comment]
Due to the lack of activity, the issue is closed.
