### ISSUE TITLE
Error restarting WebEngagePlugin

### ISSUE THREAD

**Issue by astraube** [WebEngage/webengage-flutter#31]
**New version is causing error on application restart**

- Incorrect condition

https://github.com/WebEngage/webengage-flutter/blob/6e28709da1a66a8e3c0600583397154c237db04e/android/src/main/java/com/webengage/webengage_plugin/WebEngagePlugin.java#L56

- MethodChannel is not restarting

https://github.com/WebEngage/webengage-flutter/blob/6e28709da1a66a8e3c0600583397154c237db04e/android/src/main/java/com/webengage/webengage_plugin/WebEngagePlugin.java#L57

- However the MethodCallHandler is set to null

https://github.com/WebEngage/webengage-flutter/blob/6e28709da1a66a8e3c0600583397154c237db04e/android/src/main/java/com/webengage/webengage_plugin/WebEngagePlugin.java#L376

**Comment by MilindWebEngage** [comment]
@astraube Thank you for your feedback on latest version.
You are correct  MethodChannel will not restart in some condition.
We will provided a fix and will release a new version for it.
Thank you

**Comment by BhaveshSarwarWebEngage** [comment]
Latest Version v1.2.3 has been released
