### ISSUE TITLE
iOS Webengage crash issue [WEGConfig commitWithLuid:andCuid:]

### ISSUE THREAD

**Issue by suriyaKalidoss21** [WebEngage/webengage-flutter#33]
WebEngage is crashing on iOS getting few crashes but difficult to find the root cause.

Webengage version
webengage_flutter: ^1.2.0
<img width="661" alt="Screenshot 2023-05-04 at 5 05 43 PM" src="https://user-images.githubusercontent.com/51110790/236192734-a563529a-fcb8-4f94-868f-f0d8e48a375b.png">

Attached logs for details : 
Crashed: WEGQueue (QOS: USER_INITIATED)
0  CoreFoundation                 0x83830 CFGetTypeID + 148
1  CoreFoundation                 0x27440 _flattenPlist + 72
2  CoreFoundation                 0x27690 _flattenPlist + 664
3  CoreFoundation                 0x27690 _flattenPlist + 664
4  CoreFoundation                 0x30104 __CFBinaryPlistWriteOrPresize + 260
5  CoreFoundation                 0x7dfd4 CFPropertyListWrite + 204
6  CoreFoundation                 0x92d8c CFPropertyListCreateData + 144
7  Foundation                     0x51538 +[NSPropertyListSerialization dataWithPropertyList:format:options:error:] + 52
8  WebEngage                      0x5d454 -[WEGConfig commitWithLuid:andCuid:] + 144
9  WebEngage                      0x7db44 -[WEGEvent performHooks] + 4284
10 WebEngage                      0x7be74 -[WEGEvent convertToReportableMapIfReportable] + 4608
11 WebEngage                      0xe8d0 -[WEGSyncAction main] + 180
12 Foundation                     0x7a6f0 __NSOPERATION_IS_INVOKING_MAIN__ + 16
13 Foundation                     0x3bd0c -[NSOperation start] + 708
14 Foundation                     0x3ba40 __NSOPERATIONQUEUE_IS_STARTING_AN_OPERATION__ + 16
15 Foundation                     0x41104 __NSOQSchedule_f + 172
16 libdispatch.dylib              0x24b4 _dispatch_call_block_and_release + 32
17 libdispatch.dylib              0x3fdc _dispatch_client_callout + 20
18 libdispatch.dylib              0x746c _dispatch_continuation_pop + 504
19 libdispatch.dylib              0x6ad4 _dispatch_async_redirect_invoke + 584
20 libdispatch.dylib              0x15a6c _dispatch_root_queue_drain + 396
21 libdispatch.dylib              0x16284 _dispatch_worker_thread2 + 164
22 libsystem_pthread.dylib        0xdbc _pthread_wqthread + 228
23 libsystem_pthread.dylib        0xb98 start_wqthread + 8

Full log: 
[logs.txt](https://github.com/WebEngage/webengage-flutter/files/11396928/logs.txt)

let me know any other details needed

**Comment by MilindWebEngage** [comment]
@suriyaKalidoss21 
Could you please provide me with the SDK VERSION for your app? To find the SDK VERSION, please go to the WebEngage dashboard, then to users, select any iOS user, go to the event tab, and open any event (such as Session Started). The SDK VERSION can be found there.

Please raise a ticket at [support@webengage.com](mailto:support@webengage.com) for the same and share all the details.

**Comment by suriyaKalidoss21** [comment]
sdk version : 
60200

**Comment by suriyaKalidoss21** [comment]
resolved in plugin update
