### ISSUE TITLE
Web compatibility for this package

### ISSUE THREAD

**Issue by Navdeep-Goyal** [WebEngage/webengage-flutter#37]
This flutter package is not compatible for flutter web.

**Comment by MilindWebEngage** [comment]
@Navdeep-Goyal 
The WebEngage Flutter Package, found at [LINK](https://pub.dev/packages/webengage_flutter), is specifically designed to cater to the Android and iOS platforms. It provides seamless integration with both operating systems, allowing developers to leverage the powerful features of WebEngage in their Flutter applications. Unfortunately, support for other platforms, such as Windows, macOS, or Linux, is currently not available. However, if you are developing for Android or iOS, this package offers a reliable solution for incorporating WebEngage functionalities into your Flutter projects.
