### ISSUE TITLE
MissingPluginException(No implementation found for method setDevicePushOptIn on channel webengage_flutter)

### ISSUE THREAD

**Issue by yashpalzala** [WebEngage/webengage-flutter#41]
I'm trying to integrate webengage_flutter in iOS and I get this error:

`flutter: MissingPluginException(No implementation found for method setDevicePushOptIn on channel webengage_flutter)`

 on calling `WebEngagePlugin.setUserDevicePushOptIn(permissionStatus.isGranted);`

I'm even making sure that permission is given before calling this function.

1.  I have followed official iOS integration steps - [https://docs.webengage.com/docs/flutter#3-ios-initialization](url)
2. Then I have followed the webengage's official iOS docs for push notifications [https://docs.webengage.com/docs/ios-push-messaging](url) 
**But haven't setup the Rich Push Notifications & Deeplink part (step 4,5.. onwards) though, can that be the reason?**

NOTE: I have implemented the same thing in android and it works perfectly fine.

**Version- webengage_flutter: ^1.2.4**

**Comment by MilindWebEngage** [comment]
@yashpalzala 
[Flutter Push Notifications](https://docs.webengage.com/docs/flutter-push-notifications#making-your-flutter-app-compatible-with-android-13-push-changes)
The setUserDevicePushOptIn function is only available for Android, so you need to add the condition as mentioned in the documentation.

Additionally, make sure to use the latest version of webengage_flutter, which is currently (1.3.0). You can find it on [pub.dev](https://pub.dev/packages/webengage_flutter)
