### ISSUE TITLE
iOS: Notification permission is requested right after initialising WebEngage SDK

### ISSUE THREAD

**Issue by raj-patil53** [WebEngage/webengage-flutter#45]
We want to manually request permission for push notifications later in the user journey. But, the request is being made right after first app open. The issue is present only in iOS and it works after removing WebEngage SDK initialisation:
``` 
WebEngage.sharedInstance().application(application, didFinishLaunchingWithOptions: launchOptions)
```

**Comment by MilindWebEngage** [comment]
@raj-patil53 To disable the push request from WebEngage, set autoRegister to false in didFinishLaunchingWithOptions, utilize the following code:

`WebEngage.sharedInstance().application(application, didFinishLaunchingWithOptions: launchOptions, autoRegister: false)`
For more details, refer to the [official documentation](https://docs.webengage.com/docs/ios-advanced#3-alternative-initialization).
