### ISSUE TITLE
Invalid tracking information

### ISSUE THREAD

**Issue by binSaed** [WebEngage/webengage-flutter#46]
<img width="973" alt="Screenshot 2024-05-04 at 4 59 23 AM" src="https://github.com/WebEngage/webengage-flutter/assets/33700292/a92232ed-0b05-4617-850e-61e86aeb1cc7">

**Comment by binSaed** [comment]
ITMS-91064: Invalid tracking information - A PrivacyInfo.xcprivacy file contains invalid tracking information at the following path: “Frameworks/WebEngage.framework/PrivacyInfo.xcprivacy”. NSPrivacyTracking must be true if NSPrivacyTrackingDomains isn‘t empty. Keys and values in your app’s privacy manifest must be valid. For more details about privacy manifest files, visit: https://developer.apple.com/documentation/bundleresources/privacy_manifest_files.

**Comment by MilindWebEngage** [comment]
@binSaed Please navigate to the project/ios folder, open the terminal, and run 'pod update WebEngage'. It should use the latest version, 6.8.1. The tracking issue has been fixed in WebEngage version 6.8.1.
