### ISSUE TITLE
Doesn't initialize Webengage with End of Input error

### ISSUE THREAD

**Issue by Apurba1921** [WebEngage/webengage-flutter#50]
Hi,

I configured webengage in my Flutter app according to the documentaion.
I made a MainApplication.kt alongide my existing MainActivity.kt

I made changes in my AndroidMainifest.xml according to the documentation.
I installed the "webengage_flutter" package.

Still I am getting this "**End of Input**" Exception.

![Screenshot 2024-12-03 123527](https://github.com/user-attachments/assets/d9be6cb4-9e30-4c65-abe5-a65febea4f02)

**Flutter & Dart versions**:
Flutter 3.3.9 • channel stable • https://github.com/flutter/flutter.git
Framework • revision b8f7f1f986 (2 years ago) • 2022-11-23 06:43:51 +0900
Engine • revision 8f2221fbef
Tools • Dart 2.18.5 • DevTools 2.15.0

Can I get some help fixing this error ?

Thanks!

**Comment by MilindWebEngage** [comment]
@Apurba1921 Have you added the license code and environment correctly?
https://docs.webengage.com/docs/android-getting-started#2-initialization
<img width="798" alt="Screenshot 2024-12-03 at 2 28 05 PM" src="https://github.com/user-attachments/assets/1cb1e457-d69e-4ecf-802d-ec08cee8b96b">

**Comment by Apurba1921** [comment]
Yes, I have initialized it in application tag.

**Comment by MilindWebEngage** [comment]
@Apurba1921 Could you please send your license code to the following email ID: milind.keni@webengage.com?

**Comment by Apurba1921** [comment]
Here's my license code: "~10a5ca3ab"


________________________________

**Comment by Apurba1921** [comment]
Done.

**Comment by MilindWebEngage** [comment]
@Apurba1921 You have not added the Android details on the dashboard. You need to add them first to activate your license code for Android.
Please raise a ticket at [support@webengage.com](mailto:support@webengage.com) for the same and share all the details.
